[workspace]
members = [ "client","server"]

[workspace.dependencies]
axum = "0.7.7"
axum-extra = "0.9.4"
futures = "0.3.31"
futures-util = "0.3.31"
headers = "0.4"
tokio = "1.41.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tokio-tungstenite = "0.24.0"
tower-http = "0.6.1"