services:
  database:
    image: postgres:17-bookworm
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=draft_together
    shm_size: 128mb
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d:r
  
  app:
    image: rust:1-bookworm
    volumes:
      - .:/draft_together
    environment:
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
    command: sh -c "cd draft_together && cargo run -p draft_together_server"