services:
  database:
    image: postgres:17-bookworm
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=draft_together
    shm_size: 128mb
    volumes:
      - ./back/postgres:/docker-entrypoint-initdb.d:r

  app:
    image: rust:1-bookworm
    volumes:
      - ./back:/draft_together
    environment:
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 3636:3000
    command: sh -c "cd draft_together && cargo run -p draft_together_server"
