CREATE TABLE champion (
    id SERIAL PRIMARY KEY,
    riotId VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL UNIQUE,
    defaultSkinImagePath VARCHAR(255) NOT NULL UNIQUE,
    centeredDefaultSkinImagePath VARCHAR(255) NOT NULL UNIQUE
);